var caste_list = [
  "other",
  "Abbasi",
  "Abro",
  "Arain",
  "Alvi",
  "Ansari",
  "Awan",
  "Bhils",
  "Bajwa",
  "Baloch",
  "Bugti",
  "Bukhari (Syed)",
  "Bukhari (Non-Syed)",
  "Butt",
  "Bhutto",
  "Buzdar",
  "Chaththa",
  "Dalit",
  "Dar",
  "Dogar",
  "Farooqi",
  "Farooqi-Fareedi",
  "Ghak-khar",
  "Gill",
  "Gujjar",
  "Hashmi (Not Syed)",
  "Kalash",
  "Jatoi",
  "Joiya",
  "Jutt",
  "Jutt Bajwa",
  "Jutt Dhilon",
  "Jutt Ranjha",
  "Jutt Sandhu",
  "Jutt Tarrar",
  "Jutt Virk",
  "Jutt Warriach",
  "Kamboh",
  "Kashmiri",
  "Khan",
  "Khan Khatak",
  "Khan Lodhi",
  "Khokhar",
  "Khosa",
  "Mahar",
  "Malik",
  "Malik Awan",
  "Meo",
  "Mian",
  "Mir",
  "Mughal",
  "Mughal Baig",
  "Mughal Barlas",
  "Mughal Mirza",
  "Mughal Chughtai",
  "Qureshi (Not Syed)",
  "Qureshi- Farooqi",
  "Qureshi – Siddiqui",
  "Qureshi – Usmani",
  "Raja",
  "Rajput",
  "Rajput Bhatti",
  "Rajput Chauhan",
  "Rajput Janjua",
  "Rajput Rana",
  "Rajput Rangar",
  "Siddis",
  "Sheikh",
  "Sheikh Khawaja",
  "Sheikh Ansari",
  "Sheikh Punjabi",
  "Sheikh Siddiqui",
  "Siddiqui",
  "Syed",
  "Syed - Bukhari",
  "Syed - Chishti",
  "Syed - Gilani",
  "Syed - Fatmi",
  "Syed - Hasni",
  "Syed - Hussaini",
  "Syed - Jafri",
  "Syed - Naqvi",
  "Syed - Rizvi",
  "Syed - Zaidi",
  "Usmani",
  "Yousufzai",
  "Zardari",
  "Zubairi",
];

var education_list = [
  'other'
  "illiterate",
"Under Matric",
"Matric",
"F.A / F.Sc",
"DAE-Diploma",
"DAE – Mechanical",
"DAE – Chemical",
"DAE – Architect",
"DAE-Civil",
"DAE – Electronics",
"DAE-Electrical",
"B.A",
"B.Sc",
"BS – Mass Communication",
"BS – Psychology",
"BS - Nutritionist",
"BS – Physiotherapy",
"BS – Medical Technology",

"BS – Computer Sciences",
"BS – Business Management",
"BS- Accounts",
"BS – Others",
"Engineering",
"Engineering – Mechanical",
"Engineering – Chemical",
"Engineering – Architect",
"Engineering-Civil",
"Engineering – Electronics",
"Engineering – Electrical",

"MBBS",
"MBBS-FCPS Continue",
"MBBS-FCPS",
"M.A",
"M.A English",
"MS",
"MS – Mass Communication",
"MS – Psychology",
"MS - Nutritionist",
"MS - Physiotherapy",
"MS - Medical Technology",
"MS  Business Related Subjects",
"MS - Computer Sciences",
"MS - Others",
"B. Com",
"ACCA – continue",
"ACCA – Completed",
"CA - Continue",
"CA – Complete",
"Accounts Degree",
"MBA",
"LLB",
  "PhD",
  "other",
];

var profession_list = [
  'other',
  "Non Working",
"Labor Work",
  "Office Job",
  "Other",
  "Sales & Marketing",
  "Media Related",
  "Health Related",
  "Engineering Related",
  "Property & Construction",
  "IT Related",
  "Accounts & Management",
  "Banking",
  "Lecturer",
  "School Teacher",
  "Education Related",
  "Supported by Family",
  "Chartered Accountant",
  "HR ",
  "Graphic Related",
  "Law Related",
  "Pharma Related",
  "Aviation Related",
  "other"
];



var business_list = [
  'other',
  "Property"
 "Car Dealing"
  "Import/Export",
 "Health Related",
 "Construction",
 "IT related",
  "Shop",
 "Food Related",
 "Education Related",
  "Labor Work",
 "Consultancy",
 "Entertainment",
  "Other",
];




var complexion_list = [
  "Extremely Fair",
  'Fair',
  'Medium skin',
  'Olive skin',
  'Brown skin'
];

var martialstatus_list = [
  "Never Married",
  "Married",
  "Divorced",
  "widower",
];

var lifestandard_list = [
  'poor',
  'lower middle class',
  'Middle Class',
  'Rich',
];



var gender_list = [
  'Male',
  'Female',
];

var sect_List = [
  "Other",
 "Sunni- ahl e hadith",
  "Sunni-Brailvi",
  "Sunni-Deobandi",
  "Sunni-Others",
  "Shia- Punj Imami",
  "Shia - isna ashri",
  "Shia - Others",

//  "Muslim",
//  "Athe",
//  "Bahá’í",
//  "Buddh",
//  "Christian",
//  "Confucian",
//  "Druze",
//  "Gnostic",
//  "Hindu",
//  "Jain",
//  "Juda",
//  "Rastafarian",
//  "Shinto",
//  "Sikh",
//  "Zoroastrian",
//  "Traditional African Religions",
//  "African Diaspora Religions",
//  "Indigenous American Religions",
];


  var height_list = [
    "4 feet 8 Inch",
    "4 feet 9 Inch",
    "4 feet 10 Inch",
    "4 feet 11 Inch",
    "5 feet 0 Inch",
    "5 feet 1 Inch",
    "5 feet 2 Inch",
    "5 feet 3 Inch",
    "5 feet 4 Inch",
    "5 feet 5 Inch",
    "5 feet 6 Inch",
    "5 feet 7 Inch",
    "5 feet 8 Inch",
    "5 feet 9 Inch",
    "5 feet 10 Inch",
    "5 feet 11 Inch",
    "6 feet 0 Inch",
    "6 feet 1 Inch",
    "6 feet 2 Inch",
    "6 feet 3 Inch",
    "6 feet 4 Inch",
    "6 feet 5 Inch",
    "6 feet 6 Inch",
    "6 feet 7 Inch",
    "6 feet 8 Inch",
    "6 feet 9 Inch",
  ];